name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y xvfb ffmpeg
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run pre-commit
        run: |
          pre-commit run --all-files
      - name: Run tests
        run: pytest
      - name: Smoke synthetic data generation
        run: bash scripts/synth_100.sh --ci

  nightly-evals:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run eval harness
        run: bash scripts/run_eval.sh medium

  schedule:
    if: github.repository != ''
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nightly workflow triggered via GitHub scheduling."
