apiVersion: aiplatform.googleapis.com/v1
kind: CustomJob
metadata:
  name: impossible-tower-train
jobSpec:
  workerPoolSpecs:
    - machineSpec:
        machineType: n1-standard-8
      replicaCount: 1
      containerSpec:
        imageUri: gcr.io/$PROJECT_ID/impossible-tower-trainer:latest
        command:
          - python
          - src/model/train_vertex/trainer.py
        args:
          - --train-data
          - gs://$BUCKET/datasets/itower/train
          - --eval-data
          - gs://$BUCKET/datasets/itower/val
          - --output-dir
          - gs://$BUCKET/models/itower
