from google import genai

def generate_bucket_contents(bucket_name, dataset_date):
    """Generates a list of bucket contents based on the dataset date."""
    try:
        client = genai.Client()

        prompt = f"Based on the information that the bucket {bucket_name} contains daily autogenerated datasets in the format itower/<YYYY-MM-DD>/synth_500 and that on {dataset_date} the itower-datagenerator job was executed, generate a list of likely bucket contents."

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        print(response.text)

    except Exception as e:
        print(f"Error generating bucket contents: {e}")

if __name__ == "__main__":
    bucket_name = "gs://impossible-tower-data"
    dataset_date = "2025-09-19"
    generate_bucket_contents(bucket_name, dataset_date)